### ISSUE TITLE
Could this be a PreloadingStrategy for RouterModule

### ISSUE THREAD

**Issue by GrandSchtroumpf** [mgechev/guess-angular#2]
I've experience slower building process when using the custom webpack builder. If guess.js could be implemented as a PreloadingStrategy for the RouterModule, I think it would be easier to use for Angular developer.
Is it something even possible to do ?

**Comment by mgechev** [comment]
Hey @GrandSchtroumpf, Guess.js plugs into the build process and this allows it to preform a very efficient prefetching at runtime, much more efficient compared to what's currently possible if we move the functionality as a preloading strategy.
